FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache python3 make g++
RUN npm install -g @nestjs/cli
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
ENTRYPOINT []
EXPOSE 4000
CMD ["sh", "entrypoint.dev.sh"]