FROM node:20-alpine
WORKDIR /app
# ← OBLIGATOIRE pour bcrypt
RUN apk add --no-cache python3 make g++
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 4000
CMD ["npm", "run", "start:dev"]
